config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'links#index'
  authenticate :user, -> (u) { u.admin? } do
    mount RailsAdmin::Engine => '/admin_panel', as: 'rails_admin'
  end
  resources :links
  authenticated :user do
    get 'my_links', to: 'links#my'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    if user
      if user.admin?
        can :manage, :all
      elsif user.present?
        can :manage, Link, user_id: user.id
        can :create, Tag
      end
    end
    can :read, Link
    can :read, Tag

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/concerns/roleable.rb
require 'active_support/concern'

# For cusrom roles define method @roles as array, before including Roleable
module Roleable
  extend ActiveSupport::Concern
  DEFAULT_ROLES = %w[user admin].freeze

  included do

    roles.each do |r|
      scope r, -> { where(role: r) }
    end

    roles.each do |r|
      define_method :"#{r}?" do
        role == r
      end

      define_method :"#{r}!" do
        update(role: r)
      end
    end
  end

  class_methods do
    private

    def roles
      @roles || DEFAULT_ROLES
    end
  end
end

app/models/link.rb
class Link
  URL_REGEX = /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\Z/ix.freeze

  attr_accessor :tmp_tags

  include Mongoid::Document
  field :url, type: String
  field :description, type: String

  after_initialize :load_tmp_tags

  belongs_to :user
  has_and_belongs_to_many :tags
  accepts_nested_attributes_for :tags, reject_if: :all_blank, allow_destroy: true

  validates :url, presence: true
  validates :url, format: { with: URL_REGEX }

  private

  def load_tmp_tags
    self.tmp_tags = tags.map(&:title).join(', ') unless tags.blank?
  end
end

app/models/tag.rb
class Tag
  include Mongoid::Document
  field :title, type: String
  has_and_belongs_to_many :links

  validates :title, presence: true
  validates :title, uniqueness: true
end

app/models/user.rb
class User
  include Mongoid::Document
  @roles = %w[user admin]
  include Roleable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  field :first_name,    type: String
  field :last_name,    type: String

  field :role,               type: String, default: 'user'

  has_many :links

  def full_name
    [first_name, last_name].join(' ')
  end

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from Mongoid::Errors::DocumentNotFound, with: :record_not_found
  rescue_from CanCan::AccessDenied, with: :access_denied

  private

  def record_not_found
    flash[:error] = I18n.t('messages.errors.not_found')
    redirect_back(fallback_location: root_path)
  end

  def access_denied
    flash[:warning] = I18n.t('messages.errors.access_denied')
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  load_and_authorize_resource
  before_action :set_link, only: %i[show edit update destroy]

  def index
    @tags = Tag.all
    @links =
      if params[:tag].present?
        Link::FindByTag.(tag_title: params[:tag])
      else
        Link.includes(:tags)
      end
    paginate_links
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    Link::BuildTags.(@link)
    if @link.save
      flash[:success] = I18n.t('links.successfully_created')
      redirect_to root_path
    else
      flash.now[:error] = I18n.t('links.creation_error')
      render action: :new
    end
  end

  def edit
  end

  def update
    @link.assign_attributes(link_params)
    Link::BuildTags.(@link)
    if @link.save
      flash[:success] = I18n.t('links.successfully_updated')
      redirect_to link_path(@link)
    else
      flash.now[:error] = I18n.t('links.updation_error')
      render action: :edit
    end
  end

  def destroy
    if @link.destroy
      flash[:success] = I18n.t('links.successfully_destroyed')
      redirect_to root_path
    else
      flash[:error] = I18n.t('links.can_not_destroy_because',
        message: @link.errors.full_messages.join(', '))
      redirect_to link_path(@link)
    end
  end

  def my
    @links = current_user.links
    paginate_links
    render action: :index
  end

  private

  def link_params
    params.require(:link).permit(:url, :description, :tmp_tags)
      .merge(user_id: current_user.id)
  end

  def set_link
    @link = Link.find( params[:id])
  end

  def paginate_links
    @links = @links.page(params[:page]).per(params[:per]) unless @links.blank?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
.row
  .small-12.columns
    %ul.menu
      %li{ class: "is-active" }
        %a Home
      - if can? :create, Link
        %li= link_to t('links.new'), new_link_path
      - if current_user.blank?
        %li= link_to t('menu.sign_in'), new_user_session_path
        %li= link_to t('menu.sign_up'), new_user_registration_path
      - else
        %li= link_to t('menu.sign_out'), destroy_user_session_path, method: :delete

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en"}
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : t('main_title')

    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application"
    = csrf_meta_tag

  %body
    = render 'partials/flash_messages'

    = render 'layouts/components/menu'

    = yield

app/views/layouts/components/_menu.html.haml
.row
  .small-12.columns
    %ul.menu
      %li{ class: "is-active" }
        = link_to t('menu.home'), root_url
      - if can? :create, Link
        %li= link_to t('links.new'), new_link_path
      - if current_user
        - if current_user.admin?
          %li= link_to t('menu.admin_panel'), rails_admin_path,
            data: { turbolinks: false }
        %li= link_to t('links.my'), my_links_path
      - if current_user.blank?
        %li= link_to t('menu.sign_in'), new_user_session_path
        %li= link_to t('menu.sign_up'), new_user_registration_path
      - else
        %li= link_to t('menu.sign_out'), destroy_user_session_path, method: :delete

app/views/layouts/devise.html.haml
!!! 5
%html{ :lang => "en"}
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : t('main_title')

    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application"
    = csrf_meta_tag

  %body
    = render 'partials/flash_messages'

    = render 'layouts/components/menu'

    .row
      .small-12.medium-8.large-6.medium-offset-2.large-offset-3.columns
        = yield

app/views/links/_form.html.haml
= simple_form_for @link, url: @link.persisted? ? link_path(@link) : links_path do |f|
  .row
    .small-12.columns
      = f.input :url
    .small-12.columns
      = f.input :tmp_tags
    .small-12.columns
      = f.input :description, as: :text
    .small-12.columns.text-right
      = f.submit t('buttons.save'), class: 'button'

app/views/links/edit.html.haml
.row
  .samll-12.columns
    %h3= t('links.editing')
= render 'form'

app/views/links/index.html.haml
.row
  - if @tags.blank?
    .small-12.columns.text-center
      .label.secondary= t('tags.not_found')
      %hr
  - else
    .small-12.columns
      - if params[:tag].present?
        = link_to t('links.clear_search'), links_path, class: 'label'
      - @tags.each do |tag|
        = link_to tag.title, links_path(tag: tag.title),
          class: "label#{ ' active' if tag.title == params[:tag]}"
      %hr
- if @links.blank?
  .small-12.columns.text-center
    .label.secondary= t('links.not_found')
    %hr
- else
  - @links.each do |link|
    .row
      .small-10.columns
        = link_to link.url, link.url
      .small-2.columns.text-right
        - if can?(:edit, link)
          = link_to t('links.edit'), edit_link_path(link)
        - if can?(:destroy, link)
          = link_to 'x', link_path(link), method: :delete,
            data: { confirm: t('links.destroy_confirmation', message: link.url) }

      .small-12.columns
        = truncate(link.description, length: 100, separator: ' ')
      .small-12.columns
        - link.tags.each do |tag|
          = link_to tag.title, links_path(tag: tag.title), class: 'label'
        %hr
  .row
    .small-12.columns.text-center
      = paginate @links

app/views/links/new.html.haml
.row
  .samll-12.columns
    %h3= t('links.creation')
= render 'form'

app/views/links/show.html.haml
.row
  .small-12.columns.text-center
    = link_to @link.url, @link.url, class: 'main-link'
  .small-12.columns
    = @link.description
  .small-12.columns
    - @link.tags.each do |tag|
      = link_to tag.title, links_path(tag: tag.title), class: 'label'
    %hr
  .small-12.columns.text-right
    - if can?(:edit, @link)
      = link_to t('links.edit'), edit_link_path(@link), class: 'button small'
    - if can?(:destroy, @link)
      = link_to t('links.delete'), link_path(@link), method: :delete, class: 'button small',
        data: { confirm: t('links.destroy_confirmation', message: @link.url) }

app/views/partials/_flash_messages.html.haml
- flash.each do |key, value|
    .notice{ data: { type: key, message: value } }